<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<ul class="easytabs">
    <?php $i = 0; ?>
    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
        <?php if($this->getChildHtml($_tab['alias'])
            && strlen(strip_tags(trim($this->getChildHtml($_tab['alias'])))) > 0): ?>
            <?php
                $tabTitle = $this->__($_tab['title']);
            ?>
            <li <?php echo !$i ? 'class="active first"' : '' ?>>
                <a href="#product_tabs_<?php echo $_tab['alias'] ?>" class="easytabs-anchor"><?php echo $tabTitle; ?></a>
            </li>
	    <?php $i++; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<div class="padder">
    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
        <?php if($this->getChildHtml($_tab['alias'])): ?>
            <div id="product_tabs_<?php echo $_tab['alias'] ?>_contents">
                <?php echo $this->getChildHtml($_tab['alias']); ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    new EasyTabs('.easytabs-anchor');
</script>
