<?php
    $tabs = array();
    foreach ($this->getTabs() as $_index => $_tab) {
        if (!($childHtml = $this->getChildHtml($_tab['alias']))
            || $this->isEmptyString($childHtml)) {

            continue;
        }
        $_tab['child_html'] = $childHtml;
        $_tab['title'] = $this->getTabTitle($_tab);

        $tabs[$_index] = $_tab;
    }
?>
<div class="easytabs-wrapper" id="easytabs">
    <div class="easytabs-ul-wrapper">
        <ul class="easytabs">
            <?php foreach ($tabs as $_index => $_tab) : ?>
                <li>
                    <span data-href="#product_tabs_<?php echo $_tab['alias'] ?>" class="easytabs-anchor easytabs-a easytabs-a-tab">
                        <?php if ($this->canShowAnchor()) : ?>
                            <a href="#product_tabs_<?php echo $_tab['alias'] ?>" class="easytabs-anchor-icon">#</a>
                        <?php endif ?>
                        <?php echo $this->__($_tab['title']); ?>
                    </span>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="padder easytabs-content-wrapper">
        <?php foreach ($tabs as $_index => $_tab) : ?>
            <a href="#product_tabs_<?php echo $_tab['alias'] ?>"
                class="easytabs-anchor easytabs-a easytabs-a-accordion"
            ><?php echo $this->__($_tab['title']); ?></a>
            <div class="easytabs-content"
                id="product_tabs_<?php echo $_tab['alias'] ?>_contents"
                style="display:none">
                <?php echo $_tab['child_html']; ?>
                </div>
        <?php endforeach; ?>
    </div>

    <script type="text/javascript">
        var easytabs = new EasyTabs();
    </script>
</div>
