<div class="chosen-container chosen-container-multi" style="width: 100%;">
    <ul class="chosen-choices" style="min-height: 30px; width: 60%;">
    </ul>
</div>
<script type="text/javascript">
    document.observe('click', function(e){
        var clickedEl = Event.element(e);
        if (clickedEl.hasClassName('search-choice-close')) {
            var child = clickedEl.up('.search-choice');
            child.remove();
        }
    });
</script>
