<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()):

    $grouped = (bool) $this->getIsGrouped();
    if ($grouped) {
        $setId = $_product->getAttributeSetId(); // Attribute set Id
        $groups = Mage::getModel('eav/entity_attribute_group')
            ->getResourceCollection()
            ->setAttributeSetFilter($setId)
            ->setSortOrder()
            ->load();

        $attributeCodes = array();
        foreach ($groups as $group) {
            $groupName          = $group->getAttributeGroupName();
            $groupId            = $group->getAttributeGroupId();

            $attributes = Mage::getResourceModel('catalog/product_attribute_collection')
                ->setAttributeGroupFilter($group->getId())
                ->addVisibleFilter()
                ->checkConfigurableProducts()
                ->load();
            if ($attributes->getSize() > 0) {
                foreach ($attributes->getItems() as $attribute) {
                    /* @var $child Mage_Eav_Model_Entity_Attribute */
                    $attributeCodes[$attribute->getAttributeCode()] = array(
                        'id' => $groupId,
                        'name' => $groupName,
                        'sort_order' => $group->getSortOrder()
                    );
                    // uncomment for debug
                    // if ($attribute->getIsVisibleOnFront() && $attribute->getIsUserDefined()) {
                        // $_additional[$attribute->getAttributeCode()] = array(
                        //     "label" => $attribute->getFrontendLabel(),
                        //     "value" => $attribute->getDefaultValue() . ' xx',
                        //     "code" => $attribute->getAttributeCode()
                        // );
                    // }
                }
            }
        }

        foreach ($_additional as &$data) {
            $data['group'] = isset($attributeCodes[$data['code']]) ? $attributeCodes[$data['code']] : array();
        }
        usort($_additional, function($a, $b) {
            return $a['group']['sort_order'] - $b['group']['sort_order'];
        });
    }
    $_prevGroupId = -1;
?>
<div class="box-collateral box-additional">
<?php foreach ($_additional as $_data): ?>
    <?php $_groupId = isset($_data['group']) ? $_data['group']['id'] : 0; ?>
    <?php if ($_groupId != $_prevGroupId) : ?>
        <?php $_prevGroupId = $_groupId; ?>
    <table class="data-table">
        <caption class="h2"><?php echo $grouped ? $_data['group']['name'] : '';?></caption>
        <col width="25%" />
        <col />
        <tbody>
    <?php endif; ?>
    <?php
        $_label = $this->htmlEscape($this->__($_data['label']));
        $_value = $_helper
            ->productAttribute($_product, $_data['value'], $_data['code']);
    ?>
            <tr>
                <th class="label"><?php echo $_label ?></th>
                <td class="data"><?php echo $_value ?></td>
            </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif;?>
