<?php
/**
 * Product additional attributes template
 *
 * @see TM_EasyTabs_Block_Tab_Product_Additional
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()):
    $_prevGroupId = -1;
?>
<div class="box-collateral box-additional">
<?php foreach ($_additional as $_data): ?>
    <?php $_groupId = isset($_data['group']) ? $_data['group']['id'] : 0; ?>
    <?php if ($_groupId != $_prevGroupId) : ?>
        <?php $_prevGroupId = $_groupId; ?>
    <table class="data-table">
        <caption class="h2">
            <?php echo $this->getIsGrouped() ? $_data['group']['name'] : '';?>
        </caption>
        <col width="25%" />
        <col />
        <tbody>
    <?php endif; ?>
    <?php
        $_label = $this->htmlEscape($this->__($_data['label']));
        $_value = $_helper
            ->productAttribute($_product, $_data['value'], $_data['code']);
    ?>
            <tr>
                <th class="label"><?php echo $_label ?></th>
                <td class="data"><?php echo $_value ?></td>
            </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif;?>
